### Health check
GET http://localhost:5000/api/health

##auth checks:

### Register new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "maya",
  "email": "maya@example.com",
  "password": "123456",
  "favoriteGenres": ["Fantasy", "Romance"],
  "favoriteBooks": ["Fourth Wing"]
}
### Register second user
### This request creates another user so we can test club creation
### and later test joining/leaving clubs with different users.
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Noa Levi",
  "email": "noa@example.com",
  "password": "123456",
  "favoriteGenres": ["Mystery", "Thriller"],
  "favoriteBooks": ["The Silent Patient"]
}

### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "linoy@example.com",
  "password": "123456"
}
### Login second user
### This request logs in the second user.
### Copy the accessToken from the response and use it in the next request.
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "noa@example.com",
  "password": "123456"
}

### Refresh access token
POST http://localhost:5000/api/auth/refresh-token


### Logout
POST http://localhost:5000/api/auth/logout

### Get current user
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODA5MTI5ODgsImV4cCI6MTc4MDkxMzg4OH0.PWmrbOqPSHz9ykgF4D4aUy3VZi2MgSrCFHp-54jm08w

### Update current user
PATCH http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODA5MTI5ODgsImV4cCI6MTc4MDkxMzg4OH0.PWmrbOqPSHz9ykgF4D4aUy3VZi2MgSrCFHp-54jm08w
Content-Type: application/json

{
  "favoriteBooks": ["Fourth Wing"],
  "favoriteGenres": ["Fantasy", "Romance"]
}


##club checks:

### Create a new club
### This request creates a new book club in the database.
### It requires a logged-in user, so we must send an access token.
### The server will take the logged-in user from the token and save them as:
### 1. creator - the user who created the club
### 2. first member - the creator is automatically added to members
POST http://localhost:5000/api/clubs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMDU0MTQsImV4cCI6MTc4MTAwNjMxNH0.GEr9SoA4ami3evjix9UhW8YjrurAgp9nzZ02ZPG62oE
Content-Type: application/json

{
  "name": "Fantasy Readers",
  "description": "A cozy club for fantasy book lovers",
  "genres": ["Fantasy"]
}
### Create a new club as second user
### This request creates a new book club using Noa's account.
### Because the token belongs to Noa, the server will save Noa as:
### 1. the creator of the club
### 2. the first member of the club
POST http://localhost:5000/api/clubs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI4MDQ4NmIzYzA5ZDAwNWExYjZmMTciLCJpYXQiOjE3ODEwMDc0OTQsImV4cCI6MTc4MTAwODM5NH0.7Ub50Pct_1bqW319m4bg08gwYEF8RbtiiQ8kA8PGOt0
Content-Type: application/json

{
  "name": "Mystery & Tea Club",
  "description": "A relaxed club for readers who love mysteries, thrillers, and cozy discussions.",
  "genres": ["Mystery", "Thriller"]
}
### Get all public clubs
GET http://localhost:5000/api/clubs

### Search clubs by club name
### This request searches public clubs by club name.
### It can return more than one club if several clubs match the same text.
GET http://localhost:5000/api/clubs?search=fantasy

### Filter clubs by genre
### This request returns public clubs that include the selected genre.
GET http://localhost:5000/api/clubs?genre=Fantasy

### Search clubs by creator name
### This request returns public clubs created by users whose name includes the search text.
GET http://localhost:5000/api/clubs?creator=maya

### Search clubs by name and genre together
### This request returns public clubs whose name includes the search text
### and whose genres include the selected genre.
GET http://localhost:5000/api/clubs?search=fantasy&genre=Fantasy

##books checks:

### Create a new book for a club
### This request creates a book and connects it to an existing club.
### Only the creator of the club can add books to that club.
### Replace CLUB_ID_HERE with the id of the club.
### Replace ACCESS_TOKEN_HERE with the access token of the club creator.
POST http://localhost:5000/api/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMTc3MjAsImV4cCI6MTc4MTAxODYyMH0.gsfXZ45u6R0Uyqsz6XOmSHWZwIT0zV9tDW4LVSsEB5M
Content-Type: application/json

{
  "title": "The Hobbit",
  "author": "J.R.R. Tolkien",
  "coverImage": "",
  "description": "A fantasy adventure about Bilbo Baggins and his unexpected journey.",
  "genres": ["Fantasy"],
  "totalChapters": 19,
  "club": "6a27fc8c711fc4a5878cb4a6"
}

### Create another book for Fantasy Readers
### This request creates one more book and connects it to the Fantasy Readers club.
### Only the creator of Fantasy Readers can add books to this club.
### Replace FANTASY_READERS_CLUB_ID with the id of Fantasy Readers.
### Replace MAYA_ACCESS_TOKEN_HERE with Maya's access token.
POST http://localhost:5000/api/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMTc3MjAsImV4cCI6MTc4MTAxODYyMH0.gsfXZ45u6R0Uyqsz6XOmSHWZwIT0zV9tDW4LVSsEB5M
Content-Type: application/json

{
  "title": "Harry Potter and the Philosopher's Stone",
  "author": "J.K. Rowling",
  "coverImage": "",
  "description": "A young boy discovers he is a wizard and begins his first year at Hogwarts School of Witchcraft and Wizardry.",
  "genres": ["Fantasy"],
  "totalChapters": 17,
  "club": "6a27fc8c711fc4a5878cb4a6"
}
#########################################################################################################################
### Set current book for Fantasy Readers
### This request sets a book as the current book of a club.
### Only the club creator can do this.
### If the club already has a current book, the old current book moves to previousBooks.
### Replace FANTASY_READERS_CLUB_ID with the club id.
### Replace BOOK_ID_HERE with the id of a book that belongs to this club.
### Replace MAYA_ACCESS_TOKEN_HERE with Maya's access token.
PATCH http://localhost:5000/api/clubs/6a27fc8c711fc4a5878cb4a6/current-book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMjU5NDAsImV4cCI6MTc4MTAyNjg0MH0.xVXSGVYVWWHgZ45JgroAkpXmNX5SUbBhum8s-TmfrLY
Content-Type: application/json

{
  "book": "6a282d39271b5b5c1e2f53d8"
}


### Get all books
### This request returns all books from all clubs.
GET http://localhost:5000/api/books

### Get books by club
### This request returns only the books connected to a specific club.
GET http://localhost:5000/api/books?club=6a27fc8c711fc4a5878cb4a6

### Search books by title or author
### This request searches books by title or author.
GET http://localhost:5000/api/books?search=hobbit

### Filter books by genre
### This request returns books that include the selected genre.
GET http://localhost:5000/api/books?genre=Fantasy

##reading Progress checks:

### Update my reading progress
### This request creates or updates the logged-in user's reading progress.
### If progress already exists for this user + club + book, it updates it.
### If it does not exist yet, it creates a new progress document.
### Replace ACCESS_TOKEN_HERE with the user's access token.
### Replace CLUB_ID_HERE with the club id.
### Replace BOOK_ID_HERE with the book id.
POST http://localhost:5000/api/reading-progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMjM5MDUsImV4cCI6MTc4MTAyNDgwNX0._fjbRCvWVhygPYnU-_b-Pzi_rANjSew-9ADB0sljix0
Content-Type: application/json

{
  "club": "6a27fc8c711fc4a5878cb4a6",
  "book": "6a282d39271b5b5c1e2f53d8",
  "currentChapter": 3
}

### Get my reading progress
### This request returns all reading progress documents
### that belong to the logged-in user.
GET http://localhost:5000/api/reading-progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMjM5MDUsImV4cCI6MTc4MTAyNDgwNX0._fjbRCvWVhygPYnU-_b-Pzi_rANjSew-9ADB0sljix0

### Get my reading progress by club
### This request returns the logged-in user's reading progress
### only for one specific club.
GET http://localhost:5000/api/reading-progress?club=6a27fc8c711fc4a5878cb4a6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMjM5MDUsImV4cCI6MTc4MTAyNDgwNX0._fjbRCvWVhygPYnU-_b-Pzi_rANjSew-9ADB0sljix0

### Get my reading progress by book
### This request returns the logged-in user's reading progress
### only for one specific book.
GET http://localhost:5000/api/reading-progress?book=6a282d39271b5b5c1e2f53d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMjM5MDUsImV4cCI6MTc4MTAyNDgwNX0._fjbRCvWVhygPYnU-_b-Pzi_rANjSew-9ADB0sljix0

### Complete a book and add rating
### This request updates the current chapter to the last chapter.
### The server should automatically set isCompleted to true.
### The rating is optional, but here we test saving a user rating too.
POST http://localhost:5000/api/reading-progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMjM5MDUsImV4cCI6MTc4MTAyNDgwNX0._fjbRCvWVhygPYnU-_b-Pzi_rANjSew-9ADB0sljix0
Content-Type: application/json

{
  "club": "6a27fc8c711fc4a5878cb4a6",
  "book": "6a282d39271b5b5c1e2f53d8",
  "currentChapter": 17,
  "rating": 5
}

### Try to update progress with chapter greater than total chapters
### This request should fail because the selected book has only 17 chapters.
### Expected result: 400 error.
POST http://localhost:5000/api/reading-progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMjM5MDUsImV4cCI6MTc4MTAyNDgwNX0._fjbRCvWVhygPYnU-_b-Pzi_rANjSew-9ADB0sljix0
Content-Type: application/json

{
  "club": "6a27fc8c711fc4a5878cb4a6",
  "book": "6a282d39271b5b5c1e2f53d8",
  "currentChapter": 99
}

### Delete my reading progress
### This request deletes one reading progress document.
### The user can delete only their own progress document.
### Replace PROGRESS_ID_HERE with the _id of the reading progress document.
DELETE http://localhost:5000/api/reading-progress/6a2845ff2842c92fb3ba3402
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwMjM5MDUsImV4cCI6MTc4MTAyNDgwNX0._fjbRCvWVhygPYnU-_b-Pzi_rANjSew-9ADB0sljix0

##Comments check:
### Create regular chapter comment
### This creates a normal comment connected to a specific chapter.
### It is NOT spoiler-free, so users who have not reached this chapter should see it locked.
### Replace ACCESS_TOKEN_HERE with a club member access token.
### Replace CLUB_ID_HERE with the club id.
### Replace BOOK_ID_HERE with the book id.
POST http://localhost:5000/api/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwODgxNDAsImV4cCI6MTc4MTA4OTA0MH0.EHXC5ZoWbb0WciB7KTWFJ-ZYWNMj-Xs1A4fBXJgb0Ac
Content-Type: application/json

{
  "club": "6a27fc8c711fc4a5878cb4a6",
  "book": "6a282d39271b5b5c1e2f53d8",
  "text": "I loved the way the story developed in this chapter.",
  "chapterNumber": 3,
  "isSpoilerFreeReview": false,
  "parentComment": null
}

### Create locked future chapter comment
### This creates a comment for a later chapter.
### A user whose reading progress is lower than this chapter should receive it with text: null and isLocked: true.
POST http://localhost:5000/api/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwODgxNDAsImV4cCI6MTc4MTA4OTA0MH0.EHXC5ZoWbb0WciB7KTWFJ-ZYWNMj-Xs1A4fBXJgb0Ac
Content-Type: application/json

{
  "club": "6a27fc8c711fc4a5878cb4a6",
  "book": "6a282d39271b5b5c1e2f53d8",
  "text": "This comment talks about something important that happens much later.",
  "chapterNumber": 10,
  "isSpoilerFreeReview": false,
  "parentComment": null
}

### Create spoiler-free public review
### This creates a comment/review that is safe for everyone, including guests.
### It should appear in the public comments endpoint.
POST http://localhost:5000/api/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwODgxNDAsImV4cCI6MTc4MTA4OTA0MH0.EHXC5ZoWbb0WciB7KTWFJ-ZYWNMj-Xs1A4fBXJgb0Ac
Content-Type: application/json

{
"club": "6a27fc8c711fc4a5878cb4a6",
  "book": "6a282d39271b5b5c1e2f53d8",
  "text": "A beautifully written fantasy book with a cozy and adventurous atmosphere.",
  "chapterNumber": 0,
  "isSpoilerFreeReview": true,
  "parentComment": null
}

### Get comments for logged-in user
### This returns all comments for the selected club and book.
### Comments from chapters the user has not reached should still appear,
### but with text: null and isLocked: true.
GET http://localhost:5000/api/comments?club=6a27fc8c711fc4a5878cb4a6&book=6a282d39271b5b5c1e2f53d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwODgxNDAsImV4cCI6MTc4MTA4OTA0MH0.EHXC5ZoWbb0WciB7KTWFJ-ZYWNMj-Xs1A4fBXJgb0Ac

### Get public spoiler-free comments
### This returns only spoiler-free comments.
### It does not require login and is safe for guests.
GET http://localhost:5000/api/comments/public?club=6a27fc8c711fc4a5878cb4a6&book=6a282d39271b5b5c1e2f53d8

### Toggle like comment
### Run this request once to like the comment.
### Run it again to unlike the same comment.
POST http://localhost:5000/api/comments/6a29402ee9ff4f60a16943e7/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwODgxNDAsImV4cCI6MTc4MTA4OTA0MH0.EHXC5ZoWbb0WciB7KTWFJ-ZYWNMj-Xs1A4fBXJgb0Ac

### Update my comment
### Only the comment author can update the comment.

PATCH http://localhost:5000/api/comments/6a29402ee9ff4f60a16943e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwODgxNDAsImV4cCI6MTc4MTA4OTA0MH0.EHXC5ZoWbb0WciB7KTWFJ-ZYWNMj-Xs1A4fBXJgb0Ac
Content-Type: application/json

{
  "text": "Edited comment text.",
  "chapterNumber": 3,
  "isSpoilerFreeReview": false
}

### Delete comment without replies
### If this comment has no replies, it should be permanently deleted.
DELETE http://localhost:5000/api/comments/6a29402ee9ff4f60a16943e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwODgxNDAsImV4cCI6MTc4MTA4OTA0MH0.EHXC5ZoWbb0WciB7KTWFJ-ZYWNMj-Xs1A4fBXJgb0Ac


##user checks:

### Search users by username
### This request searches users by username.
### It requires login.
### It does NOT return email, because this is user-search data.
GET http://localhost:5000/api/users/search?username=maya
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwOTY2MjcsImV4cCI6MTc4MTA5NzUyN30.qgUh-Ztx0G2rt8zkOr4Kz1zR1ZvRux73eC1lOeWpE0U

### Get my own user profile
### This request returns the logged-in user's own profile.
### Because it is my own profile, the response should include email.
GET http://localhost:5000/api/users/6a254803d797fe4b9cbd4261
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwOTY2MjcsImV4cCI6MTc4MTA5NzUyN30.qgUh-Ztx0G2rt8zkOr4Kz1zR1ZvRux73eC1lOeWpE0U

### Get another user's profile
### This request returns another user's profile.
### Because it is not my own profile, the response should NOT include email.
GET http://localhost:5000/api/users/6a280486b3c09d005a1b6f17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI1NDgwM2Q3OTdmZTRiOWNiZDQyNjEiLCJpYXQiOjE3ODEwOTY2MjcsImV4cCI6MTc4MTA5NzUyN30.qgUh-Ztx0G2rt8zkOr4Kz1zR1ZvRux73eC1lOeWpE0U


### Get user's clubs
### This request returns all clubs where the selected user is a member.
GET http://localhost:5000/api/users/6a254803d797fe4b9cbd4261/clubs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI4MDQ4NmIzYzA5ZDAwNWExYjZmMTciLCJpYXQiOjE3ODEwOTY2NzUsImV4cCI6MTc4MTA5NzU3NX0.tX9SCwfTe2aONbWv62mwxQUxPYOCX5jRjkbeuA0rHSg

### Get user's currently reading books
### This request returns ReadingProgress documents where isCompleted is false.
GET http://localhost:5000/api/users/6a254803d797fe4b9cbd4261/currently-reading
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI4MDQ4NmIzYzA5ZDAwNWExYjZmMTciLCJpYXQiOjE3ODEwOTY2NzUsImV4cCI6MTc4MTA5NzU3NX0.tX9SCwfTe2aONbWv62mwxQUxPYOCX5jRjkbeuA0rHSg

### Get user's completed books
### This request returns ReadingProgress documents where isCompleted is true.
### It can include rating if the user rated the book.
GET http://localhost:5000/api/users/6a254803d797fe4b9cbd4261/completed-books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI4MDQ4NmIzYzA5ZDAwNWExYjZmMTciLCJpYXQiOjE3ODEwOTY2NzUsImV4cCI6MTc4MTA5NzU3NX0.tX9SCwfTe2aONbWv62mwxQUxPYOCX5jRjkbeuA0rHSg

### Try to get user profile without login
### This request should fail because user routes are protected.
### Expected result: 401 Unauthorized.
GET http://localhost:5000/api/users/6a280486b3c09d005a1b6f17




### Create next-read poll
POST http://localhost:5000/api/clubs/6a32e74bafb8950a6536e36a/polls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJlNjQ5NDFkYjJiOTEyYzE1ZDcyYmQiLCJpYXQiOjE3ODIxMTM4MjAsImV4cCI6MTc4MjExNDcyMH0.V9qOZ96xH9BGvX7uHLTQgXo8__Pd2avvFeJYVne0TF8
Content-Type: application/json

{
  "question": "What should we read next?",
  "closesAt": "2026-07-01T20:00:00.000Z",
  "options": [
    {
      "title": "Babel",
      "author": "R.F. Kuang",
      "coverImage": "",
      "description": "A historical fantasy novel about language, power, and resistance."
    },
    {
      "title": "The Night Circus",
      "author": "Erin Morgenstern",
      "coverImage": "",
      "description": "A magical competition between two young illusionists."
    }
  ]
}

### Get current poll
GET http://localhost:5000/api/clubs/6a32e74bafb8950a6536e36a/polls/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJlNjQ5NDFkYjJiOTEyYzE1ZDcyYmQiLCJpYXQiOjE3ODIxMTM4MjAsImV4cCI6MTc4MjExNDcyMH0.V9qOZ96xH9BGvX7uHLTQgXo8__Pd2avvFeJYVne0TF8

### Vote in poll
POST http://localhost:5000/api/clubs/6a32e74bafb8950a6536e36a/polls/6a38e63f911289957a923f81/vote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJlNjQ5NDFkYjJiOTEyYzE1ZDcyYmQiLCJpYXQiOjE3ODIxMTM4MjAsImV4cCI6MTc4MjExNDcyMH0.V9qOZ96xH9BGvX7uHLTQgXo8__Pd2avvFeJYVne0TF8
Content-Type: application/json

{
  "optionId": "6a38e63f911289957a923f82"
}

### Announce poll winner
POST http://localhost:5000/api/clubs/6a32e74bafb8950a6536e36a/polls/6a38e63f911289957a923f81/announce-winner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJlNjQ5NDFkYjJiOTEyYzE1ZDcyYmQiLCJpYXQiOjE3ODIxMjU5OTEsImV4cCI6MTc4MjEyNjg5MX0.DFggZMds_C1tWKEEoCZkq7XSvfrBAGD5frxt6JtX7fA
Content-Type: application/json

{
  "optionId": "6a38e63f911289957a923f82",
  "totalChapters": 36
}

### Set winner book as current book
PATCH http://localhost:5000/api/clubs/6a32e74bafb8950a6536e36a/polls/6a38e63f911289957a923f81/set-winner-current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJlNjQ5NDFkYjJiOTEyYzE1ZDcyYmQiLCJpYXQiOjE3ODIxMjU5OTEsImV4cCI6MTc4MjEyNjg5MX0.DFggZMds_C1tWKEEoCZkq7XSvfrBAGD5frxt6JtX7fA


### Upload profile image
PUT http://localhost:5000/api/users/me/profile-image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJlNjQ5NDFkYjJiOTEyYzE1ZDcyYmQiLCJpYXQiOjE3ODI2NDE0OTIsImV4cCI6MTc4MjY0MjM5Mn0.aicaKobQaGBeXQNzHz3TV-bV_4-4stnMuB8O1cXs-08
Content-Type: multipart/form-data; boundary=----LiveBookBoundary

------LiveBookBoundary
Content-Disposition: form-data; name="image"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./avatar.jpg
------LiveBookBoundary--